# fly.toml app configuration file generated for alkanes-compiler-service on 2025-10-21T17:24:54-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'alkanes-compiler-service'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[[checks]]
  type = "http"
  name = "healthcheck"
  interval = "10s"
  timeout = "2s"
  path = "/health"

[experimental]
  allowed_public_ports = []
  auto_rollback = true